-- MySQL Script generated by MySQL Workbench
-- Sun Nov 26 18:36:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `senha` VARCHAR(64) NOT NULL,
  `status` ENUM('pending', 'blocked', 'active', 'inactive') NOT NULL,
  `criadoEm` DATETIME NOT NULL,
  `modificadoEm` DATETIME NOT NULL,
  `tipo` ENUM('ADM', 'AUTOR', 'CLIENTE') NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_Cliente_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_Cliente_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cartao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cartao` (
  `idCartao` INT NOT NULL AUTO_INCREMENT,
  `nomeImpresso` VARCHAR(64) NOT NULL,
  `numero` VARCHAR(32) NOT NULL,
  `cvv` INT NOT NULL,
  `dataVencimento` DATE NOT NULL,
  `criadoEm` DATETIME NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idCartao`),
  INDEX `fk_Cartao_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cartao_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Autor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idUsuario` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `endereço` VARCHAR(255) NOT NULL,
  `numeroAgencia` VARCHAR(16) NOT NULL,
  `numeroConta` VARCHAR(16) NOT NULL,
  INDEX `fk_Autor_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cupom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cupom` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cupom` (
  `idCupom` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `status` ENUM('active', 'inactive', 'expired') NOT NULL DEFAULT 'active',
  `porcentagem` FLOAT(4,2) NOT NULL,
  `dataExpiracao` DATE NULL,
  `criadoEm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modificadoEM` DATETIME NOT NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCupom`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_Cupom_Autor1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Cupom_Autor1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Autor` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Genero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Genero` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenero`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EBook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EBook` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EBook` (
  `idEBook` INT NOT NULL AUTO_INCREMENT,
  `idAutor` INT NOT NULL,
  `nome` VARCHAR(128) NOT NULL,
  `status` ENUM('pending', 'active', 'inactive', 'rejected') NOT NULL,
  `preco` FLOAT(10,2) NOT NULL,
  `sinopse` TEXT NOT NULL,
  `capa` VARCHAR(255) NULL,
  `qtdPaginas` INT NULL,
  `idioma` VARCHAR(64) NULL,
  `formato` VARCHAR(45) NULL DEFAULT 'PDF',
  `tamanhoEmMB` INT NULL,
  `anoLancamento` VARCHAR(45) NULL,
  `motivoRejeicao` VARCHAR(45) NULL,
  `criadoEm` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modificadoEm` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `outrosAutores` VARCHAR(255) NULL,
  PRIMARY KEY (`idEBook`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GeneroEBook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GeneroEBook` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GeneroEBook` (
  `idGenero` INT NOT NULL,
  `idEBook` INT NOT NULL,
  INDEX `fk_GeneroEBook_Genero_idx` (`idGenero` ASC) VISIBLE,
  INDEX `fk_GeneroEBook_EBook1_idx` (`idEBook` ASC) VISIBLE,
  PRIMARY KEY (`idGenero`, `idEBook`),
  CONSTRAINT `fk_GeneroEBook_Genero`
    FOREIGN KEY (`idGenero`)
    REFERENCES `mydb`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GeneroEBook_EBook1`
    FOREIGN KEY (`idEBook`)
    REFERENCES `mydb`.`EBook` (`idEBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `meioPagamento` ENUM('pix', 'credito') NOT NULL,
  `data` DATE NOT NULL DEFAULT CURRENT_DATE,
  `status` ENUM('canceled', 'pending', 'approved', 'failed') NOT NULL DEFAULT 'pending',
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemPedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ItemPedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ItemPedido` (
  `idCupom` INT NULL,
  `idEBook` INT NOT NULL,
  `idPedido` INT NOT NULL,
  `valorUnitario` FLOAT(10,2) NOT NULL,
  `valorTotal` FLOAT(10,2) NOT NULL,
  INDEX `fk_ItemPedido_Cupom1_idx` (`idCupom` ASC) VISIBLE,
  INDEX `fk_ItemPedido_EBook1_idx` (`idEBook` ASC) VISIBLE,
  INDEX `fk_ItemPedido_Pedido1_idx` (`idPedido` ASC) VISIBLE,
  PRIMARY KEY (`idEBook`, `idPedido`),
  CONSTRAINT `fk_ItemPedido_Cupom1`
    FOREIGN KEY (`idCupom`)
    REFERENCES `mydb`.`Cupom` (`idCupom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemPedido_EBook1`
    FOREIGN KEY (`idEBook`)
    REFERENCES `mydb`.`EBook` (`idEBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemPedido_Pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Carrinho` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Carrinho` (
  `idCarrinho` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `modificadoEm` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCarrinho`),
  INDEX `fk_Carrinho_Cliente1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Carrinho_Cliente1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Cliente` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemCarrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ItemCarrinho` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ItemCarrinho` (
  `idEBook` INT NOT NULL,
  `dCarrinho` INT NOT NULL,
  INDEX `fk_ItemCarrinho_EBook1_idx` (`idEBook` ASC) VISIBLE,
  INDEX `fk_ItemCarrinho_Carrinho1_idx` (`dCarrinho` ASC) VISIBLE,
  PRIMARY KEY (`idEBook`, `dCarrinho`),
  CONSTRAINT `fk_ItemCarrinho_EBook1`
    FOREIGN KEY (`idEBook`)
    REFERENCES `mydb`.`EBook` (`idEBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemCarrinho_Carrinho1`
    FOREIGN KEY (`dCarrinho`)
    REFERENCES `mydb`.`Carrinho` (`idCarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `super` TINYINT NOT NULL,
  `idUsuario` INT NOT NULL,
  INDEX `fk_Administrador_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_Administrador_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Biblioteca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Biblioteca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Biblioteca` (
  `idCliente` INT NOT NULL,
  `idEBook` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `idEBook`),
  INDEX `fk_Cliente_has_EBook_EBook1_idx` (`idEBook` ASC) VISIBLE,
  INDEX `fk_Cliente_has_EBook_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_EBook_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_EBook_EBook1`
    FOREIGN KEY (`idEBook`)
    REFERENCES `mydb`.`EBook` (`idEBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
